apiVersion: v1
kind: ServiceAccount
metadata:
  name: elf-owl
  namespace: {{ .Release.Namespace }}
  labels:
    app: elf-owl
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
