apiVersion: v1
kind: Service
metadata:
  name: elf-owl
  namespace: elf-owl-system
  labels:
    app: elf-owl
spec:
  type: ClusterIP
  selector:
    app: elf-owl
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: health
      port: 9091
      targetPort: 9091
      protocol: TCP
